export const QUERY_KEYS = {
    FETCH_ACTIVE_GOALS: "FETCH_ACTIVE_GOALS",
    FETCH_TOMORROW_GOALS: "FETCH_TOMORROW_GOALS",
    FETCH_NEXT_7_DAY_GOALS: "FETCH_NEXT_7_DAY_GOALS",
    FETCH_VISUALIZATIONS: "FETCH_VISUALIZATIONS",
};