name: Deploy Firebase Functions

on:
  push:
    branches:
      - main  # Deploy only on the main branch
    paths:
      - 'functions/backend/**'  # Trigger only if files in this folder change

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20  # Use the Node.js version required by Firebase

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Install dependencies
        run: cd functions/backend && npm install

      - name: Build dependencies
        run: cd functions/backend && npm run build

      - name: Authenticate Firebase using Token
        run: firebase use --token ${{ secrets.FIREBASE_CI_TOKEN }}

      - name: Deploy Firebase Functions
        run: firebase deploy --only functions --token ${{ secrets.FIREBASE_CI_TOKEN }}
